#!/usr/bin/env python
import sys
import subprocess
import os

DEVNULL = open(os.devnull, 'w')

for thing in ["*requirements*", "*migrations*"]:

    diff_requirements = f"git diff ORIG_HEAD HEAD --exit-code -- {thing}"

    exit_code = subprocess.call(diff_requirements.split(), stdout=DEVNULL)
    if exit_code == 1:
        print(f"🚨🚨🚨 {thing} changed and needs to be actioned! 🚨🚨🚨")
